language: csharp
sudo: required
dist: xenial
#solution: Terminal.Gui.Elmish.sln
script:
  #- tsh_version=1.4.0-pre1
  #- msbuild /t:Restore $TRAVIS_BUILD_DIR/Terminal.Gui.Elmish.sln
  - cd $TRAVIS_BUILD_DIR/
  - cd src
  - cd Terminal.Gui.Elmish
  - dotnet build
  #- dotnet build Terminal.Gui.Elmish.sln --framework netcoreapp2.0
  #- msbuild /p:Configuration=Release Terminal.Gui.Elmish.sln
#mono: latest
dotnet: 6.0.300
os: "linux"